=== qwerty541/firmware-updater/firmware-updater/config.schema.json
{
    "$schema": "https://json-schema.org/draft-04/schema#",
    "type": "object",
    "required": [
        "$schema",
        "firmwareLocalStoragePath",
        "firmwareFileNameWithoutVersion",
        "remoteFirmwareStorageServer",
        "systemdFirmwareServiceConfigurationFilePath"
    ],
    "properties": {
        "$schema": {
            "type": "string"
        },
        "firmwareLocalStoragePath": {
            "type": "string"
        },
        "firmwareFileNameWithoutVersion": {
            "type": "string"
        },
        "remoteFirmwareStorageServer": {
            "type": "object",
            "required": [
                "hostname",
                "port",
                "path"
            ],
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "port": {
                    "type": "integer",
                    "maximum": 65535
                },
                "path": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "systemdFirmwareServiceConfigurationFilePath": {
            "type": "string"
        }
    },
    "additionalProperties": false
}

=== qwerty541/firmware-updater/firmware-updater/config.example.json
{
    "$schema": "./config.schema.json",
    "firmwareLocalStoragePath": "/home/username/projects/firmware-updater/firmware-storage/",
    "firmwareFileNameWithoutVersion": "firmware-v",
    "remoteFirmwareStorageServer": {
        "hostname": "127.0.0.1",
        "port": 8080,
        "path": "/"
    },
    "systemdFirmwareServiceConfigurationFilePath": "/etc/systemd/system/fake_firmware.service"
}
